import type {Metadata} from "next";import Image from "next/image";import Link from "next/link";import {notFound} from "next/navigation";import Gallery from "../../services/Gallery";import {selfEmployedScreens} from "../../services/data";import {freeSolutions,getFreeSolution} from "../data";
export function generateStaticParams(){return freeSolutions.map(x=>({slug:x.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const x=getFreeSolution(slug);if(!x)return {};const canonical=`https://autobiz-vb.github.io/free-solutions/${x.slug}/`;return {title:x.title,description:x.short,alternates:{canonical},openGraph:{title:x.title,description:x.short,url:canonical,type:"website",locale:"ru_RU"}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const x=getFreeSolution(slug);if(!x)notFound();const isSelfEmployed=slug==="uchet-samozanyatogo";const realScreens=selfEmployedScreens.map(([file,caption,alt])=>({src:`/cases/${file}`,caption,alt}));return <main className="innerPage">
  <header className="innerHeader"><div className="container header"><Link className="brand" href="/"><Image src="/automation-cube.png" width={42} height={42} alt="" unoptimized/><span><b>Автоматизация</b><small>бизнес-процессов</small></span></Link><nav><Link href="/">Главная</Link><Link className="mobileCaseLink" href="/cases">Кейсы</Link><Link className="active" href="/free-solutions">Бесплатные решения</Link><Link className="navCta" href="/#contact">Обсудить задачу</Link></nav></div></header>
  <section className="detailHero"><div className="container detailHeroGrid"><div><Link className="backLink" href="/free-solutions">← Все бесплатные решения</Link><p className="kicker">{x.category} · Бесплатно</p><h1>{x.title}</h1><p className="detailLead">{x.short}</p><div className="actions"><a className="btn primary" href="https://t.me/VasiliyPF" target="_blank" rel="noreferrer">Получить бесплатно ↗</a><a className="btn light" href="#screens">Посмотреть скриншоты</a></div><small className="linkNote">Прямая ссылка на копирование таблицы появится после размещения готового шаблона.</small></div>{isSelfEmployed?<Image className="detailCover" src="/cases/self-employed-01-dashboard.png" width={1200} height={760} alt="Панель таблицы «Учёт самозанятого»" unoptimized priority/>:<Sheet title={x.title}/>}</div></section>
  <section className="section detailInfo"><div className="container infoGrid"><div><p className="kicker">Что внутри</p><h2>Готовая основа для ежедневной работы</h2><p>{x.forWhom}. Шаблон можно использовать как основу и адаптировать под текущий процесс.</p>{isSelfEmployed&&<p className="truthNote">Таблица не интегрируется с сервисом «Мой налог» и не создаёт чеки автоматически. Пользователь создаёт чек в официальном сервисе и вручную отмечает его в таблице.</p>}</div><ul>{x.features.map(f=><li key={f}>✓ <span>{f}</span></li>)}</ul></div></section>
  <section className="section screenshots" id="screens"><div className="container"><p className="kicker">Скриншоты</p><h2>Как выглядит решение</h2>{isSelfEmployed?<Gallery shots={realScreens}/>:<div className="screenGrid">{["Основной рабочий лист","Фильтры и статусы","Итоговый обзор"].map((c,i)=><figure key={c}><Sheet compact tone={i+1}/><figcaption>{c}<small>Демонстрационный экран</small></figcaption></figure>)}</div>}</div></section>
  <section className="catalogCta"><div className="container"><div><p className="kicker">Получение решения</p><h2>Запросите шаблон или закажите адаптацию</h2></div><a className="btn primary" href="https://t.me/VasiliyPF" target="_blank" rel="noreferrer">Получить бесплатно ↗</a></div></section>
</main>}
function Sheet({title,compact,tone}:{title?:string,compact?:boolean,tone?:number}){return <div className={`largeSheet ${compact?"compact":""} preview${tone||1}`}><div className="sheetBar"><i/><i/><i/></div>{title&&<b>{title}</b>}<div className="tableHead"><span>Дата</span><span>Задача</span><span>Статус</span></div>{[1,2,3,4,5].map(i=><div className="tableLine" key={i}><span/><span/><span/></div>)}</div>}
